# Generated by Django 3.1 on 2020-09-19 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot_logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('asked_question', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotSoftwareLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('executed_function', models.CharField(max_length=50)),
                ('error_message', models.CharField(max_length=300)),
                ('logging_level', models.IntegerField(choices=[(0, 'Debug'), (1, 'Info'), (2, 'Warn'), (3, 'Error'), (4, 'Fatal')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CalculatedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('simularity', models.FloatField(default=0.0)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_logic.answer')),
                ('chatbot_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_logging.chatbotconversationlog')),
            ],
        ),
    ]
