# Generated by Django 3.1 on 2020-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_logging', '0002_calculatedanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconversationlog',
            name='context_factor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatbotconversationlog',
            name='similarity_factor',
            field=models.FloatField(default=0.0),
        ),
    ]
