# Generated by Django 3.1 on 2020-09-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('similarity_factor', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('context_factor', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('matching_method', models.CharField(choices=[('cosine', 'Cosine Matching'), ('spacy', 'Spacy Matching')], default='cosine', max_length=6)),
                ('greeting_text', models.CharField(max_length=255)),
                ('noanswer_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'AdminSettings',
            },
        ),
    ]
