# Generated by Django 4.2.1 on 2023-06-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='mail_timeout_in_seconds',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='number_of_quality_test_answers',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='similarity_mail_threshold',
            field=models.FloatField(default=0.2),
        ),
    ]
