# Generated by Django 4.2.1 on 2023-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_adminsettings_mail_timeout_in_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='employee_joined_text',
            field=models.CharField(default='Ein Mitarbeiter ist der Unterhaltung beigetreten.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='employee_left_text',
            field=models.CharField(default='Der Mitarbeiter hat die Unterhaltung verlassen.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='user_left_text',
            field=models.CharField(default='Der Nutzer hat die Unterhaltung beendet.', max_length=255),
            preserve_default=False,
        ),
    ]
