# Generated by Django 4.2.1 on 2023-07-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_adminsettings_employee_joined_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='mail_request_text',
            field=models.CharField(default='hi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='mail_sent_text',
            field=models.CharField(default='hi', max_length=255),
            preserve_default=False,
        ),
    ]
