# Generated by Django 4.2.1 on 2023-07-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_adminsettings_mail_request_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='mail_input_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='mail_invalid_input_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
