# Generated by Django 3.1 on 2020-09-19 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.CharField(max_length=600)),
            ],
            options={
                'ordering': ['answer_text'],
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('context_text', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['context_text'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('similarity_factor', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('context_factor', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('matching_method', models.CharField(choices=[('cosine', 'Cosine Matching'), ('spacy', 'Spacy Matching')], default='cosine', max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.CharField(max_length=300)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_logic.answer')),
                ('context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_logic.context')),
            ],
            options={
                'ordering': ['question_text'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('keyword_text', models.CharField(max_length=30)),
                ('question', models.ManyToManyField(to='chatbot_logic.Question')),
            ],
            options={
                'ordering': ['keyword_text'],
            },
        ),
    ]
