# Generated by Django 3.1 on 2020-09-13 09:06

from chatbot_logic.models import Answer, Context, Keyword, Question
from django.db import migrations, connection
import os

import_path = './chatbot_logic/sql/'


def load_data_from_sql(file):
    sql = open(import_path + file, encoding='utf8').read()

    sql_statements = sql.split(';')

    for sql_statement in sql_statements:
        with connection.cursor() as c:
            c.execute(sql_statement)


def truncate_all(apps, schema_editor):
    Answer.objects.all().delete()
    Context.objects.all().delete()
    Keyword.objects.all().delete()
    Question.objects.all().delete()


def insert_data(apps, schema_editor):
    sql_files = os.listdir(import_path)

    for file in sql_files:
        load_data_from_sql(file)


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_logic', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(truncate_all),
        migrations.RunPython(insert_data),
    ]
