# Generated by Django 3.1 on 2020-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_logic', '0002_insert_data'),
    ]

    operations = [
    ]
