# Generated by Django 3.1 on 2023-06-03 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_logic', '0003_auto_20201003_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Chat Sessions',
            },
        ),
    ]
