# Generated by Django 4.2.1 on 2023-06-18 08:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot_logic', '0004_chatsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('chat_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_logic.chatsession')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'manualChats',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modifier_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=600)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_logic.manualchat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chat Messages',
            },
        ),
    ]
