# Generated by Django 4.2.1 on 2023-06-20 19:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot_logic', '0005_manualchat_chatmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManualChat',
            new_name='Chat',
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name_plural': 'Chats'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='from_guest',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmailSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('chat_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_logic.chatsession')),
            ],
        ),
    ]
